spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:mibookstore-api
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    h2:
        console.enabled: true


#spring.datasource.url= jdbc:oracle:thin:@localhost:1521:xe
#
#spring.datasource.username=system
#spring.datasource.password=1234
#
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
#
#spring.datasource.driver.class-name=oracle.jdbc.OracleDriver
#
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#
#spring.jackson.serialization.fail-on-empty-beans=false
